services:

  # ==========================================================
  # FASTAPI
  # ==========================================================

  api:

    build: .

    container_name: youtube_research_api

    ports:
      - "8000:8000"

    volumes:
      - ./app:/app/app

    environment:

      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/youtube_research

    env_file:
      - .env

    dns:
      - 10.3.0.101
      - 10.20.1.21
      - 10.230.102.86
      - 8.8.8.8

    depends_on:

      postgres:
        condition: service_healthy


  # ==========================================================
  # POSTGRES + PGVECTOR
  # ==========================================================

  postgres:

    image: pgvector/pgvector:pg16

    container_name: youtube_research_postgres

    environment:

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: postgres

      POSTGRES_DB: youtube_research

    ports:

      - "5432:5432"

    volumes:

      - postgres_data:/var/lib/postgresql/data

    healthcheck:

      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d youtube_research"
        ]

      interval: 5s

      timeout: 5s

      retries: 5

      start_period: 5s


# ============================================================
# PERSISTENT VOLUMES
# ============================================================

volumes:

  postgres_data: