"""
Pydantic schemas for the 3-agent YouTube research system.

Architecture:

    Agent 1
    Planner + YouTube Research
            ↓
    YouTubeResearchResult
            ↓
    Agent 2
    RAG + Context Analysis + Ranking
            ↓
    ResourceAnalysis
            ↓
    Agent 3
    Final Report
            ↓
    FinalReport
"""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


# ============================================================
# AGENT 1 — RESEARCH REQUEST
# ============================================================


class VideoFields(BaseModel):
    """
    Controls which YouTube fields Agent 1 should collect.
    """

    title: bool = True

    description: bool = False

    url: bool = True

    channel: bool = True

    published_at: bool = False

    views: bool = False

    likes: bool = False

    comments: bool = False

    transcript: bool = False


class YouTubeResearchRequest(BaseModel):
    """
    Structured research plan generated by Agent 1's
    planner component.
    """

    topic: str = Field(
        min_length=1,
        description=(
            "The topic or search query to search on YouTube."
        ),
    )

    video_count: int = Field(
        default=3,
        ge=1,
        le=20,
        description=(
            "Number of YouTube videos to collect."
        ),
    )

    search_videos: bool = Field(
        default=True,
    )

    get_details: bool = Field(
        default=True,
    )

    get_transcript: bool = Field(
        default=True,
    )

    fields: VideoFields = Field(
        default_factory=VideoFields,
    )


# ============================================================
# AGENT 1 — RAW VIDEO RESULT
# ============================================================


class YouTubeVideoResult(BaseModel):
    """
    One collected YouTube video.

    This is the raw research data produced by
    Agent 1 for a single video.
    """

    video_id: str

    title: Optional[str] = None

    description: Optional[str] = None

    url: Optional[str] = None

    channel: Optional[str] = None

    published_at: Optional[str] = None

    views: Optional[int] = None

    likes: Optional[int] = None

    comments: Optional[int] = None

    transcript: Optional[str] = None

    transcript_available: bool = False

    transcript_language: Optional[str] = None


# ============================================================
# AGENT 1 — COMPLETE OUTPUT
# ============================================================


class YouTubeResearchResult(BaseModel):
    """
    Complete output of Agent 1.

    Contains both:
        1. The research request
        2. The collected YouTube videos
    """

    research_request: YouTubeResearchRequest

    videos: list[
        YouTubeVideoResult
    ] = Field(
        default_factory=list,
    )


# ============================================================
# AGENT 2 — RESOURCE EVALUATION
# ============================================================


class ResourceEvaluation(BaseModel):
    """
    Evaluation + ranking of one YouTube resource.

    Agent 2 generates this using:
        - YouTube metadata
        - RAG transcript context
        - User research question

    Ranking is included here because the separate
    ResourceRanking agent has been removed.
    """

    rank: int = Field(
        ge=1,
        description=(
            "Final rank of the resource."
        ),
    )

    video_id: str

    title: str

    relevance_score: float = Field(
        ge=0,
        le=10,
    )

    educational_quality_score: float = Field(
        ge=0,
        le=10,
    )

    coverage_score: float = Field(
        ge=0,
        le=10,
    )

    beginner_friendly: bool

    concepts_covered: list[str] = Field(
        default_factory=list,
    )

    strengths: list[str] = Field(
        default_factory=list,
    )

    weaknesses: list[str] = Field(
        default_factory=list,
    )

    recommendation_reason: str = Field(
        description="Concise pedagogical reason why the learner should watch this video. Never mention 'Agent 1', 'Agent 2', or internal agent numbers."
    )

    overall_score: float = Field(
        ge=0,
        le=10,
    )


# ============================================================
# AGENT 2 — COMPLETE OUTPUT
# ============================================================


class ResourceAnalysis(BaseModel):
    """
    Complete output of Agent 2.

    Contains all analyzed and ranked resources.
    """

    evaluations: list[
        ResourceEvaluation
    ] = Field(
        default_factory=list,
    )

    ranking_summary: str = Field(
        default="",
        description="Comparative pedagogical summary of the evaluated resources. Never mention 'Agent 1', 'Agent 2', or internal agent numbers."
    )


# ============================================================
# AGENT 3 — FINAL REPORT RESOURCE
# ============================================================


class FinalReportResource(BaseModel):
    """
    Final representation of one recommended
    YouTube resource inside the report.

    Agent 3 receives ranked resources from Agent 2
    and preserves their factual information.
    """

    rank: int

    video_id: str

    title: str

    url: str

    channel: Optional[str] = None

    published_at: Optional[str] = None

    description: Optional[str] = None

    views: Optional[int] = None

    likes: Optional[int] = None

    comments: Optional[int] = None

    transcript: Optional[str] = None

    transcript_available: bool = False

    transcript_language: Optional[str] = None

    relevance_score: float = Field(
        ge=0,
        le=10,
    )

    educational_quality_score: float = Field(
        ge=0,
        le=10,
    )

    coverage_score: float = Field(
        ge=0,
        le=10,
    )

    beginner_friendly: bool

    concepts_covered: list[str] = Field(
        default_factory=list,
    )

    strengths: list[str] = Field(
        default_factory=list,
    )

    weaknesses: list[str] = Field(
        default_factory=list,
    )

    overall_score: float = Field(
        ge=0,
        le=10,
    )

    recommendation_reason: str


# ============================================================
# AGENT 3 — FINAL REPORT
# ============================================================


class FinalReport(BaseModel):
    """
    Final output generated by Agent 3.
    """

    # --------------------------------------------------------
    # RESEARCH QUESTION
    # --------------------------------------------------------

    research_question: str

    # --------------------------------------------------------
    # EXECUTIVE SUMMARY
    # --------------------------------------------------------

    executive_summary: str

    # --------------------------------------------------------
    # RECOMMENDED RESOURCES
    # --------------------------------------------------------

    recommended_resources: list[
        FinalReportResource
    ] = Field(
        default_factory=list,
    )

    # --------------------------------------------------------
    # LEARNING PATH
    # --------------------------------------------------------

    learning_path: list[str] = Field(
        default_factory=list,
    )

    # --------------------------------------------------------
    # KEY TOPICS
    # --------------------------------------------------------

    key_topics: list[str] = Field(
        default_factory=list,
    )

    # --------------------------------------------------------
    # METHODOLOGY
    # --------------------------------------------------------

    methodology: str = Field(
        description=(
            "Brief, unified summary (2-3 concise sentences) of the research methodology: "
            "semantic retrieval of tutorials, full transcript indexing with pgvector hybrid search, "
            "and multi-dimensional pedagogical evaluation. NEVER mention 'Agent 1', 'Agent 2', or internal agent numbers."
        )
    )

    # --------------------------------------------------------
    # LIMITATIONS
    # --------------------------------------------------------

    limitations: list[str] = Field(
        default_factory=list,
        description=(
            "2-3 brief, user-friendly limitations supported by the data (e.g., transcript availability, "
            "framework version evolution). NEVER mention internal pipeline stages or agent numbers."
        ),
    )

    # --------------------------------------------------------
    # CONCLUSION
    # --------------------------------------------------------

    conclusion: str = Field(
        description=(
            "Engaging, user-friendly, and actionable learning verdict written in an encouraging mentor tone. "
            "Highlights where the learner should start (primary recommendation), how to combine complementary resources, "
            "and practical next steps. NEVER mention 'Agent 1', 'Agent 2', or robotic evaluation formulas."
        )
    )
    

class ResearchAPIRequest(BaseModel):

    query: str = Field(
        min_length=1,
        description="Research question."
    )

    video_count: int = Field(
        default=3,
        ge=1,
        le=20,
    )


class ResearchAPIResponse(BaseModel):

    success: bool

    report: FinalReport

    research_result: YouTubeResearchResult

    analysis: ResourceAnalysis


class RenameHistoryRequest(BaseModel):

    query: str = Field(
        min_length=1,
        description="New title/query for the research run."
    )